### ISSUE TITLE
Latest NuGet Package

### ISSUE THREAD

**Issue by mjohnson0580** [RefreshingIO/hangfire-ravendb#20]
Hello,

When you get a chance could you please publish the latest NuGet package.

Many thanks

**Comment by mjohnson0580** [comment]
Also just submitted pull request #21 to update to latest stable Hangfire and RavenDB versions

**Comment by AustinWinstanley** [comment]
Pushed 2.2.0 to Nuget with all the latest changes and an upgrade to Visual Studio 2017. Thanks for y'all's work.
